name: lotomania-cron

on:
  schedule:
    - cron: "30 23 * * 1,3,5"   # 20:30 BRT (23:30 UTC) seg/qua/sex
  workflow_dispatch: {}          # permite rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step opcional só para confirmar o valor efetivo da URL (senha mascarada)
      - name: Debug POSTGRES_URL (mascarado)
        run: |
          python - <<'PY'
          import os, re
          u = os.getenv("POSTGRES_URL","")
          u_mask = re.sub(r'://([^:]+):[^@]+@', r'://\\1:***@', u)
          print("POSTGRES_URL efetivo:", u_mask)
          PY
        env:
          POSTGRES_URL: "postgres://postgres.mgwvavsjxzwflibcjzhd:CtPrJ5nOpomcjuJV@aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require"

      - name: Run script
        env:
          # ---- VARIÁVEIS COM VALORES PREENCHIDOS ----
          POSTGRES_URL: "postgres://postgres.mgwvavsjxzwflibcjzhd:CtPrJ5nOpomcjuJV@aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require"
          SMTP_HOST: "smtp-relay.brevo.com"
          SMTP_PORT: "587"
          SMTP_USER: "9712be001@smtp-brevo.com"
          SMTP_PASS: "aVAwYKIWRD8hx47p"

          # ---- VARIÁVEIS NÃO SECRETAS ----
          COMMIT: "false"                         # troque para "true" quando terminar os testes
          SMTP_NAME: "NewStore Sorteios"
          APP_NAME: "NewStore Sorteios"
          ADMIN_EMAIL: "newrecreio@gmail.com"
          LOTOMANIA_ENDPOINT: "https://servicebus2.caixa.gov.br/portaldeloterias/api/lotomania"
        run: python main.py
